#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat << EOF
signrelease 0.0.0

Easy automated release signing.

Usage: signrelease <repo>[:tag] <pgpkey>

Examples:
    signrelease getumbrel/umbrel Umbrel
    signrelease getumbrel/umbrel pgp@getumbrel.com
    signrelease getumbrel/umbrel:latest Umbrel
    signrelease getumbrel/umbrel:v0.1.2 Umbrel

GitHub: https://github.com/lukechilds/signrelease
EOF
}

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      log "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

# Parses user/repo or user/repo:tag into GitHub release url
get_release_url () {
  repo="$(echo ${1} | cut -d ':' -f 1)"
  if [[ "${1}" == *":"* ]]; then
    tag="$(echo ${1} | cut -d ':' -f 2)"
  else
    tag="latest"
  fi

  echo "https://api.github.com/repos/${repo}/releases/${tag}"
}

main () {
  # Check deps before running any commands
  check_dependencies

  # Make sure params are set
  if [[ -z ${1+x} ]] || [[ -z ${2+x} ]]; then
    show_help
    exit 1
  fi

  repo=$1
  pgp_key=$2

  release_url=$(get_release_url $repo)
}

main $@
