#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat << EOF
signrelease 0.0.0

Easy automated release signing.

Usage: signrelease <tag> <pgpkey>

Examples:
    signrelease v0.1.2 Umbrel
    signrelease v0.1.2 pgp@getumbrel.com

GitHub: https://github.com/lukechilds/signrelease
EOF
}

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      log "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

main () {
  # Check deps before running any commands
  check_dependencies

  # Make sure params are set
  if [[ -z ${1+x} ]] || [[ -z ${2+x} ]]; then
    show_help
    exit 1
  fi

  tag=$1
  pgp_key=$2

  repo=$(basename $(git rev-parse --show-toplevel))

  temp_dir="$(mktemp -d)"

  github_name="${repo}-${tag#"v"}"
  git archive --format=tar.gz -o "${temp_dir}/${github_name}.tar.gz" "${tag}"
  git archive --format=zip -o "${temp_dir}/${github_name}.zip" "${tag}"
}

main $@
